In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp
from random import randint

coding challenge at lecture 12:
1.create 2 4x6 matrics of random numbers
2. use a for loop to compute thr dot products between corrsponding columns

In [ ]:
n=4
m=6
#create a 4 on 6 matrix
a=np.random.rand(n,m)   
b=np.random.rand(n,m)
print(a)
print(a[:,0])
#create an empty matrix
c=np.zeros(6)
for i in range(m):
    c[i]=np.dot(a[:,i],b[:,i])
c
    

1. generate 2 100-elemnts row vector. compute a with b and then b with a.
2. generate 2 2-elemnts integer row vector. compute a with b and then b with

In [ ]:
#generate a 100 element vector
x=np.random.randn(100)
y=np.random.randn(100)
#write the for loop in one line
# x=np.array([x[i]*100 for i in range(100)])
# b=np.array([b[i]*100 for i in range(100)])
plt.plot(x,'o')
plt.plot(y,'x')
plt.plot(np.dot(x,y),'v')

In [ ]:
v1=np.array([2,4,-3])
v2=np.array([0,-3,-3])
ang=np.arccos(np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2)))

#draw them
fig=plt.figure()
ax=fig.gca(projection='3d')
ax.plot([0,v1[0]],[0,v1[1]],[0,v1[2]],'r')
ax.plot([0,v2[0]],[0,v2[1]],[0,v2[2]],'b')
ax.plot([0,v1[0]+v2[0]],[0,v1[1]+v2[1]],[0,v1[2]+v2[2]],'g')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_xlim(-6,6)
ax.set_ylim(-6,6)
ax.set_zlim(-6,6)
plt.show()


code chalenge lecture 16

In [ ]:
#proof the cauchy schwarz inequality
a=np.random.rand(100)
b=np.random.rand(100)
for i in range(100):
    a[i]*=100
np.abs(np.dot(a,b))



In [ ]:
#obtuse angle
a=[1,-2]
b=[2,3]
c=[0,2]
#calculate the angle between a and b and a and c and b and c and show the result in degrees
ang1=np.arccos(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)))*180/np.pi
ang2=np.arccos(np.dot(a,c)/(np.linalg.norm(a)*np.linalg.norm(c)))*180/np.pi
ang3=np.arccos(np.dot(b,c)/(np.linalg.norm(b)*np.linalg.norm(c)))*180/np.pi
print(ang1,ang2,ang3)

1. create 2 random (R4) vectors
2. comput the length of each vector and the magnitude of their dot product
3. compute the unit vector of each vector 
4. compute the magnitude of each vector dot product

In [ ]:
n=4
v1=50*(np.random.rand(n))
v2=50*(np.random.rand(n))
print(v1,v2)
#cunoute the length of v1 and v2
v1L=np.dot(v1,v1)**0.5
v2L=np.dot(v2,v2)**0.5
v1v2m=np.dot(v1L,v2L)

print(v1L,v2L,v1v2m)
v1mu=1/v1L
v2mu=1/v2L
print(v1mu,v2mu)
print(v1mu*v1L,v2mu*v2L)

In [ ]:
arrays=[]
for i in range(5):
    a=randint(1,10)
    b=randint(1,10)
    if a>b:
        temp=a
        a=b
        b=temp
    m=np.random.randint(10,20,size=(a,b))
    arrays.append(m)


In [ ]:
r={}
#find all the matrices with the same size
for i in range(len(arrays)):
    for j in range(i+1,len(arrays)):
        if arrays[i].shape==arrays[j].shape:
            r[i,j]=arrays[i]
print(arrays[0],arrays[0]*2)
    


code challenge lecture 35
1.test for some MxN matricies whether s(A+B)== sA +sB 

In [ ]:
A=np.random.randn(4,3)
B=np.random.randn(4,3)
c=int(np.random.randn()*100)
res1=c*(A+B)
res2=c*A+c*B
print(A)
print('-------')
print(A)

code challenge 39
1. determine whether the trace of tr(A) +tr(B) is equal to the trace of tr(A+B)
2. generate random scalar a and determine the relationship of tr(a*A) and tr(a*B)

In [ ]:
m=randint(0,10)
n=randint(0,10)
print(m,n)
A=np.random.randn(6,3)
B=np.random.randn(3,4)
a=randint(1,10)
# trA=np.trace(A)
# trB=np.trace(B)
# trAB=np.trace(A+B)
# print(trA,trB,trA+trB,trAB)
# traA=np.trace(a*A)

# print(traA,a*trA)

print(A)
print('-------')
print(B)
print('-------')
mul=np.matmul(A,B)

print(mul,mul.shape)

code challenge 43:
1. generate 2 matrices A and B
2. build the product matrix layer-wise (for loop)
3. implement the matrix multiplication directly
4. compute the results

In [ ]:
m=randint(1,10)
n=randint(1,10)
A=np.random.randn(m,n)
B=np.random.randn(n,m)
#build the product matrix layer-wise (for loop)
C=np.zeros((m,m))
for i in range(n):
    C+=np.outer(A[:,i],B[i,:])
D=A@B
print(C==D)

In [ ]:
A=np.array([[1,0,0],[0,10,0],[0,0,100]])
D=np.random.randn(3,3)
print(D)
D@A

code challenge 49:
1.

In [ ]:
#generate a circle of dots with radius 1
n=100
theta=np.linspace(0,2*np.pi,n)
x=np.cos(theta)
y=np.sin(theta)
plt.plot(x,y,'o')
#create 2x2 matrix 
A=np.array([[1,2],[3,4]])
#multiply the matrix with the coordinates
B=np.array([x,y])
C=np.matmul(A,B)
plt.plot(C[0],C[1],'x')
#try with various matrices
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
C=np.matmul(A,B)
print(C)
#try with singular matrix
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
C=np.matmul(A,B)
plt.show()

code challenge 53:
1. create two symetric matrices
2. cmpute sum,multiplication, and hadamard multiplication
3. determine if the result is still symmetric

In [ ]:
#create two symetric matrices
m=3
A=np.random.randn(m,m)
ATA=A.T@A
B=np.random.randn(m,m)
BTB=B.T@B
#cmpute sum,multiplication, and hadamard multiplication
C=ATA+BTB
D=ATA@BTB
E=ATA*BTB
print(C)
print(D)
print(E)



1. create 2 new matrix, one is full matrix, and the other is diagonal matrix
2. multiply each matrix by itself,

In [ ]:
m=4
A=np.random.randn(m,m)
#create a digonal matrix with the diagonal elements of A
B=np.diag(np.diag(A))
print(A),print()
print(A@A),print()
print(A*A),print()
# print(B),print()
# print(B@B),print()
# print(B*B),print()

In [ ]:
#create symetric matrix
m=4
A=np.random.randn(m,m)
ATA=np.matmul(A,A.T)
print(ATA)
#create  a skew-symetric matrix
B=np.array([[0,1,-1],[-1,0,1],[1,-1,0]])
print(B)
#create a random matrix
C=np.random.randn(m,m)
print(C)
#mix the matrices A,B
# D=ATA@B
# print(D)

In [ ]:
#create a 50x50 matrix with random numbers
A=np.random.randn(50,80)
rank=np.linalg.matrix_rank(A)
rank
#create a 9 degree random polynomial


#find the roots of the polynomial
r=np.roots(p)
print(p)
#evaluate the polynomial at 50 points
x=np.linspace(-1,1,50)
y=p(x)
#plot the polynomial
plt.plot(x,y)
#plot the polynomial with noise
y=y+np.random.randn(50)
plt.plot(x,y,'o')
#fit the polynomial to the noisy data
pfit=np.polyfit(x,y,9)
#evaluate the fitted polynomial at 50 points
yfit=np.polyval(pfit,x)
#plot the fitted polynomial
plt.plot(x,yfit)
plt.show()

In [ ]:
A=np.random.randn(10,4)
B=np.random.randn(4,10)
C=A@B
print(C.shape)
print(np.linalg.matrix_rank(C))


In [ ]:
def generalize_matrix(M,N,r):
    A=np.random.randn(M,N)
    B=np.random.randn(N,M)
    C=A@B
    return C

In [ ]:
m=2
n=5
A=np.random.randn(m,n)
B=np.random.randn(m,n)
AtA=A.T@A
BtB=B.T@B
r_A=np.linalg.matrix_rank(A)
r_B=np.linalg.matrix_rank(B)
r_AtA=np.linalg.matrix_rank(AtA)
r_BtB=np.linalg.matrix_rank(BtB)
print(r_A,r_B,r_AtA,r_BtB)

In [ ]:
#create a column vector
x=np.array([[-3],[1],[5]])
mt=np.array([[3,0],[5,2],[1,2]])
#detemine whether the vector is in the column space of the matrix
# print(np.linalg.matrix_rank(mt))
# print(np.linalg.matrix_rank(np.hstack((mt,x))))
#determine whether the vector is in the row space of the matrix
# print(np.linalg.matrix_rank(mt.T))
# print(np.linalg.matrix_rank(np.vstack((mt.T,x.T))))
x2=np.array([[1],[7],[3]])
mt2=np.array([[0,0],[5,2],[1,2]])
print(np.linalg.matrix_rank(mt2))
print(np.linalg.matrix_rank(np.hstack((mt2,x2))))
print(mt2.T@x2)



code challenge 85:
do a RREF of diffrant matrices (random)
1. squre
2. rectangles (wide,tall)
3. linear dependencies

In [ ]:
m=3
n=6
A=sp.Matrix(np.random.randn(m,m))
B=sp.Matrix(np.random.randn(m,n))
C=sp.Matrix(np.random.randn(n,m))
rref_a=A.rref()
rref_b=B.rref()
rref_c=C.rref()
print(np.array(A))
print('*'*20)
print(np.array(rref_a[0]))
print('-----------------------------')
print(np.array(B))
print('*'*20)
print(np.array(rref_b[0]))
print('-----------------------------')
print(np.array(C))
print('*'*20)
print(np.array(rref_c[0]))

In [ ]:
A=np.random.randn(2,2)
detA=np.linalg.det(A)
print(detA)
B=np.array([[1,2],[3,6]])
print(np.linalg.det(B))
m=40
C=np.random.randn(m,m)
#make a linearly dependent matrix
C[2,:]=C[0,:]+C[1,:]
#print the rank of the matrix C
print(np.linalg.matrix_rank(C))
print(np.linalg.det(C))


In [ ]:
A=np.random.randn(6,6)
print(np.linalg.det(A))
#swap the first and second rows
A[[0,1]]=A[[1,0]]
print(np.linalg.det(A))
#swap the third and forth row
A[[2,3]]=A[[3,2]]
print(np.linalg.det(A))




In [ ]:
#create hang man game
import random
import string
#create a list of words 
words=['apple','banana','orange','grape','watermelon','strawberry','pineapple','mango','kiwi','pear','peach','cherry','blueberry','raspberry','lemon','lime','coconut','avocado','tomato','cucumber','carrot','potato','pepper','onion','garlic','celery','broccoli','cauliflower','spinach','lettuce','asparagus','mushroom','corn','zucchini','cabbage','bean','pea','eggplant','sweet potato','yam','pumpkin','squash','radish','turnip','ginger','garlic','honeydew','melon','grapefruit','pomegranate','apricot','plum','nectarine','fig','date','olive','artichoke','sweet pepper','chili pepper','okra','kale','collard greens','brussel sprouts','mustard greens','turnip greens','rutabaga','turnip','beet','cantaloupe','carambola','durian','jackfruit','lychee','mangosteen','star fruit','tamarind','water chestnut','yautia','plantain','taro','sweet corn','sweet pea','sweet potato','sweet pepper','sweet onion','sweet basil','sweet cherry','sweet pea','sweet']
#choose a random word from the list
word=random.choice(words)
#convert the word to a list
word=list(word)
#convert the word to a seT
word_set=set(word)



code challenge 101
1. create diagonal matrix
2. compute the inverse of the diagonal matrix


In [ ]:
# m>n for left inverse,
# m<n for right inverse
#if i swip the m and n here all the code is broken
m = 3
n = 6

# create matrices
A = np.random.randn(m,n)
AtA = A.T@A
AAt = A@A.T

# inspect ranks
print('Shape of A^TA:', np.shape(AtA) )
print('Rank of A^TA:', np.linalg.matrix_rank(AtA) )
print('Shape of AA^T:', np.shape(AAt) )
print('Rank of AA^T:', np.linalg.matrix_rank(AAt) ) 

# left inverse
Aleft = np.linalg.inv(AtA)@A.T

# right inverse
Aright = A.T@np.linalg.inv(AAt)

# now test!
I_left  = Aleft  @ A
I_right = A @ Aright

print(I_left), print(' ')
print(I_right), print(' ')


# and then test using the inverse function
AtA_inv = np.linalg.inv(AtA)
I_AtA   = AtA_inv @ AtA

AAt_inv = np.linalg.inv(AAt)
I_AAt   = AAt_inv @ AAt

print(I_AtA), print(' ')
print(I_AAt)

In [ ]:
#function to determine if a matrix is invertible
def is_invertible(A):
    #if the rank of the matrix is equal to the number of rows and columns
    if np.linalg.matrix_rank(A)==A.shape[0]:
        return True
    else:
        return False
#function to determine if a matrix is singular
def is_singular(A):
    #if the rank of the matrix is equal to the number of rows and columns
    if np.linalg.matrix_rank(A)==A.shape[0]:
        return False
    else:
        return True
for i in range(100):
    m=np.random.randint(1,10)
    A=np.random.randn(m,m)
    if is_invertible(A):
        print('A is invertible')
        print(np.linalg.det(A))
    if is_singular(A):
        print('A is singular')


projection defenition:
beta=(A.T@b)/(A.T@a)
where A is a matrix, and b is a vector, and beta is is the point between the two A and b


In [ ]:

a=np.array([[1,2],[3,4]])

#print the projection of b onto the column space of a
row1=a[1,:]
row0=a[0,:]
beta=row0.T@row1/(row0.T@row0)
beta

projection in more general <br>
A is a matrix <br>
b is a vector between A and b<br>
x is a point<br>
A.T(b-Ax)=0<br>

In [ ]:
m=6
n=4
#vector b
b=np.random.randn(m,1)
A=np.random.randn(m,n)
#solve the projection problem using the pseudoinverse of A
x=np.linalg.pinv(A)@b
x1=np.linalg.inv(A.T@A)@A.T@b
x2=np.linalg.solve(A.T@A,A.T@b)
print(x,'\n')

print(x1,'\n')
print(x2,   '\n')

the vector to be compute<br>
w=[2,3]<br>
the refrence vector<br>
v=[4,0]<br>
1. compute w-parallel to v<br>
2. compute w-orthogonal to v <br>
3. confirm results algebraically (sum to w orthgonal components)<br>
plot all four vectors<br>

In [ ]:
w=np.array([2,3])
v=np.array([4,0])
beta=np.dot(v,w)/np.dot(v,v)
w_par_v=beta*v
w_perp_v=w-w_par_v
print((w_par_v+w_perp_v)-w)
print(np.dot(w_par_v,w_perp_v))

plt.plot([0,w[0]],[0,w[1]],'r',linewidth=3)
plt.plot([0,v[0]],[0,v[1]],'b',linewidth=3)
plt.plot([0,w_par_v[0]],[0,w_par_v[1]],'r--',linewidth=3)
plt.plot([0,w_perp_v[0]],[0,w_perp_v[1]],'r:',linewidth=3)
plt.grid()
plt.axis([-5,5,-5,5])
plt.show()


In [ ]:
n=2
a=29.6*n
b=52.7*n
temp=a*a+b*b
c=np.sqrt(temp)
#convert to inches
c=c/2.54
c

implementation of gram-schmidt algorithm
1. start with squre matrix
2. check if Q@Q.T is equal to the I
3. check for qr

In [ ]:
m=4
n=2
A=np.random.randn(m,m)

#get the qr decomposition of A
Q,R=np.linalg.qr(A)
#compute the norm of the difference between A and Q@R
print(Q@Q.T)


In [ ]:
#test of inverse very large matrix
m=2
n=m
A=np.random.randn(m,n)
print(A)
plt.imshow(A)
#multiply A by scalar 10
A=A*10
Ainv=np.linalg.inv(A)
Ainv2=np.linalg.pinv(A)
print(A)
print(Ainv)
#plot the A matrix and the inverse


# plt.imshow(Ainv)

    
plt.imshow(A)


In [ ]:
# [[ 3.96754678 14.38249894]
#  [ 3.82256477 12.051023  ]]
# [[-1.68192073  2.00731698]
#  [ 0.5335025  -0.55373715]]
a=3.96754678
b=14.38249894
c=-1.68192073
d=0.5335025
print(a*c+b*d)

In [ ]:
# data
data = np.array([[-4,0,-3,1,2,8,5,8]]).T
N    = len(data)

# design matrix
X = np.ones([N,1])
# fit the model
b = np.linalg.solve(X.T@X,X.T@data)

# compare against the mean
m = np.mean(data)

# print the results
print(b,m)

In [ ]:
# compute the model-predicted values
yHat = X@b

# plot data and model prediction
plt.plot(np.arange(1,N+1),data,'bs-',label='Data')
plt.plot(np.arange(1,N+1),yHat,'ro--',label='Model pred.')

plt.legend()
plt.show()

In [ ]:
# new design matrix
X = np.array([np.arange(0,N)]).T

# fit the model
b = np.linalg.solve(X.T@X,X.T@data)

# compute the model-predicted values
yHat = X@b

# plot data and model prediction
plt.plot(np.arange(1,N+1),data,'bs-',label='Data')
plt.plot(np.arange(1,N+1),yHat,'ro--',label='Model pred.')

plt.legend()
plt.show()
print("matan")

In [ ]:

# design matrix
X = np.concatenate( [np.ones([N,1]),np.array([np.arange(0,N)]).T],axis=1)
# fit the model
b = np.linalg.solve(X.T@X,X.T@data)

# compute the model-predicted values
yHat = X@b

# plot data and model prediction
plt.plot(np.arange(1,N+1),data,'bs-',label='Data')
plt.plot(np.arange(1,N+1),yHat,'ro--',label='Model pred.')

plt.legend()
plt.show()

In [ ]:
## now with nonlinearity in the design matrix

# design matrix
X = np.concatenate( [np.ones([N,1]),np.array([np.arange(0,N)**2]).T],axis=1)
# fit the model
b = np.linalg.solve(X.T@X,X.T@data)

# compute the model-predicted values
yHat = X@b

# plot data and model prediction
plt.plot(np.arange(1,N+1),data,'bs-',label='Data')
plt.plot(np.arange(1,N+1),yHat,'ro--',label='Model pred.')

plt.legend()
plt.show()

1. generate random data (matrix X and vector y)
2. solve for beta using QR decomposition
3. compute the QR result against the standard left inverse

In [ ]:
m=10
n=6
X=np.random.randn(m,n)
y=np.random.randn(m,1)
beta1=(np.linalg.solve(X.T@X,X.T@y))
Q,R=np.linalg.qr(X)
beta2=np.linalg.solve(R.T@R,(Q@R).T@y)
print(beta1,'\n')
print(beta2)

In [ ]:
#crete a random full rank matrix of integers
m=3
n=3
A=np.random.randint(0,10,(m,n))
eig=np.linalg.eigvals(A)
print(eig)

code challenge 131
1. create a 2X2 matrix and get the eigenvalues
2. do the following steps for NXN matrix
3. do the following steps for lower and upper matrix

In [ ]:
#crete a diagonal matrix
m=5
n=2
A=np.diag([2,1])
print("print A:" ,A)
eigA=np.linalg.eigvals(A)
print("print eigA: ",eigA)
b=np.random.randint(0,10,size=(m))
print("prtint b: ",b)
B=np.diag(b)
print("print B",B)
eigB=np.linalg.eigvals(B)
print("print eigB: ",eigB)
triAu=np.triu(b)
triAl=np.tril(b)
print("print triU: \n",triAu)
print("print triL: \n",triAl)

code challenge 132
1. generate a large matrix of 40X40 extrct the eigenvalues and plot
2. reapte this a lot og time and plot the eigenvalues in the same plot

In [ ]:
n=40
res=[]
for i in range(n):
    A=np.random.randint(1,100,(n,n))
    eigA=np.linalg.eigvals(A)
    plt.plot(eigA)
#plot the eigenvalues


In [ ]:
m=2
n=4
E=np.random.randn(n,n)
Q,R=np.linalg.eig(E)

D=np.array([[3,1],[4,6]])
eigD=np.linalg.eig(D)
# print(eigD)
A=np.array([[1,2,3],[4,3,7],[3,3,6]])
eigA=np.linalg.eig(A)
for i in eigA[0]:
    print(round(i))

In [ ]:
A=np.random.randint(1,10,(n,n))
# print(np.dot(A,A.T))
# print(A@A.T)
eigA=np.linalg.eig(A)
# print(eigA[0])
# print(eigA[1])
# print(A)
# print(A@A@A@A)
C=np.array([[-2,2,-3],[-4,1,-6],[-1,-2,0]])
C=np.random.randn(2,2)
mulC=np.linalg.matrix_power(C,2)
print(mulC)

In [ ]:
n=5
m=3
A=np.random.randint(1,10,(n,m))
B=np.random.randint(1,10,(n,m))
A=A.T@A
B=B.T@B
eigA=np.linalg.eig(A-B)
eigB=np.linalg.eig(A@A-A@B-B@A+B@B)
print(np.round(eigA[0]**2,3))
print(np.round(eigB[0],3))



code challenge 142:
1. create a 5x5 random matrix
2. make it symmetric
3. get the eigenvalues and the eigenvectors
4. convert to column vector the eigenvector
5. get the outer product of the eigenvector
6. 

In [66]:
n=5
A=np.random.randint(1,10,(n,n))
print(A)
A=A.T+A
print(A)
eigA=np.linalg.eig(A)
V=(eigA[1])
print(V)
v=V[:,0]
v=v.reshape(n,1)
v
outer=np.outer(v,v)
norm=np.linalg.norm(outer)
norm


[[3 3 8 6 1]
 [1 2 6 7 8]
 [7 7 3 5 2]
 [6 3 4 2 9]
 [7 1 5 6 6]]
[[ 6  4 15 12  8]
 [ 4  4 13 10  9]
 [15 13  6  9  7]
 [12 10  9  4 15]
 [ 8  9  7 15 12]]
[[ 0.43192956  0.41348522  0.58779103  0.54481921 -0.01185544]
 [ 0.38482917  0.0465441  -0.76740763  0.48397247 -0.16308384]
 [ 0.45974591  0.53113189 -0.17803572 -0.56698145  0.39162217]
 [ 0.46923567 -0.21007699  0.14194397 -0.38213273 -0.75466021]
 [ 0.48352347 -0.70755225  0.11722809  0.03806944  0.50038301]]


1.0000000000000002

In [32]:
def generate_singular_matrix(n=2):
    res=[]
    for i in range(n):
        res.append(np.random.randint(1,10,(1,n)))
    res[1]=res[0]*randint(1,10)
    return np.concatenate(res,axis=0)

E=generate_singular_matrix(randint(2,10 ))
print(E)
detE=np.linalg.det(E)
print(detE)
eigE=np.linalg.eig(E)
print(eigE[0])
tr=np.trace(E)
tr
sum_eigval=np.sum(eigE[0])
print(tr,sum_eigval)


[[3 6 7 6 7]
 [7 1 3 5 1]
 [5 6 5 9 7]
 [9 3 9 7 9]
 [2 8 2 2 9]]
5348.000000000002
[27.51857342+0.j         -3.3549758 +2.39646448j -3.3549758 -2.39646448j
  2.09568909+2.65342703j  2.09568909-2.65342703j]
25 (25.000000000000036+0j)
