In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp

coding challenge at lecture 12:
1.create 2 4x6 matrics of random numbers
2. use a for loop to compute thr dot products between corrsponding columns

In [15]:
n=4
m=6
#create a 4 on 6 matrix
a=np.random.rand(n,m)   
b=np.random.rand(n,m)
print(a)
print(a[:,0])
#create an empty matrix
c=np.zeros(6)
for i in range(m):
    c[i]=np.dot(a[:,i],b[:,i])
c
    

[[0.47967995 0.65406672 0.92311199 0.72641563 0.18141983 0.47936796]
 [0.37773704 0.1314351  0.99728832 0.51182526 0.43463839 0.12971525]
 [0.07552214 0.94605872 0.33703923 0.33709415 0.98103304 0.92603893]
 [0.84312165 0.2842116  0.68785814 0.28120773 0.11942502 0.25147343]]
[0.47967995 0.37773704 0.07552214 0.84312165]


array([0.75136048, 1.01740764, 2.04619602, 1.10125069, 0.542287  ,
       1.0410748 ])